# Этап сборки с Java 21
FROM gradle:8.11-jdk21 AS builder

WORKDIR /app

# Копируем исходники
COPY . .

# Даем права и собираем
RUN chmod +x gradlew
RUN ./gradlew clean buildFatJar --no-daemon

# Финальный образ с Java 21
FROM eclipse-temurin:23-jre-alpine

WORKDIR /app

# Копируем собранный JAR
COPY --from=builder /app/build/libs/*-all.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
